### ISSUE TITLE
Divide by 0 with OMP_NUM_THREADS=1

### ISSUE THREAD

**Issue by jimpo** [0xPolygonHermez/goldilocks#15]
This line https://github.com/0xPolygonHermez/goldilocks/blob/8390ceb5678935d29df8e28156c604a9149cfb45/src/poseidon_goldilocks.cpp#L154 causes a divide by 0 error. `numThreads` gets assigned to 0 and this is passed to `parcpy`.

**Comment by rickb80** [comment]
Adressed
